# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: would eat again
email: wouldeatagain@gmail.com
description: >
  Delicious meatless and allergy-friendly recipes you'll eat more than once
baseurl: ""
images_path: "/assets"
url: "http://wouldeatagain.ca"
twitter_username: wouldeatagain
# Build settings
markdown: kramdown
permalink: "/:year/:month/:day/:title"
